---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-op-metrics
  namespace: flux-system
spec:
  targetNamespace: piraeus-datastore
  commonMetadata:
    labels:
      app.kubernetes.io/name: piraeus-op
  path: ./config/extras/monitoring/kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: piraeus
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
