apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:bmqAGbpHyZG/VnW20PZr6JOrwLoa1OykWvnnWTQ/yuv+2Qnq,iv:u3M/9qKjvDhEeEHzixidqDAlt7dC+mRqR2N/8okgzOE=,tag:gx+D6w2nMJjILIBOgCZwSw==,type:str]
    credentials.json: ENC[AES256_GCM,data:EDEhslEo4PEt71xlG3xuU6V2DBR3jDlk/uNtB9AFqTRSa4ks+fmVXOI/JCtOHs2rARzxibBUyv3pcJkMaI3nbXBKT5guOPyC8IV+X8dws/+0DusPLsLy7txTa+DrVYcHTAMq/3IR3GhO7Z83H9I8e7Ahb83yaQy/QMa2JOU1GE9FsaA=,iv:b1iq1MqfE69HG0bSqnNhqBh5vec6ZqdJ7axux5BF/rs=,tag:lYMpNyE/L6WPxMMuiQICTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOUhwR0J1SndQRXZzb1Ux
            dVllUkh6c211ZnByWFZNUURGMDFESzRtK2dRCmx3TW5uNk5nQVF2UDBYOGxBLzRH
            RFg4RWJqRCtXc29iMHhJT1BqQ2FXV1UKLS0tIC9TLzVUYVZ5dTFHN0svRjZZWlhi
            c3ZWbkV0dnpubnp6eVJ1K0RRYmhPREEKPmx9BtkHz+1Ez4N0WwyT950fVyskne4l
            XrYwBqF9P4/sgQH0Otv1bi1Y4LFcgs8tA9ge5gzvgOW4ExhZ3rC3xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T13:07:09Z"
    mac: ENC[AES256_GCM,data:OYIaULWYfTSCpTKUgSWpQA8wlxgBiCjnV72P559yn31VytFjNlTJ3p4sFn39AZxyMXG4XmBNX6z6e3jCAli/UKoiqrFdm6791RIyQOrIdJdlxEsqwR8ScEdJTgAvImAyYAMyXtwrTWOAjHwXfl3a4TXhKzpjlch3Jz4JsCHuLjU=,iv:qse2YpyZzbsFvY3GtgbVVRE+2IH+KCZZncwxnAnCRmM=,tag:dGT6MmEcQCGOwto9E085HQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
