apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:dwneJakf4LCrSIqXcG4mhMIcR05F7KRprSQlzcTfeN/Q2YAo,iv:cSvzY4lfJehvnOwtVe2R3cers55I8oekNsBJ4NDEUk4=,tag:L6AZMA3hf1A2shsHfnLWWg==,type:str]
    credentials.json: ENC[AES256_GCM,data:IpMhI5xu5McsOgQZfnZY7ZGeV2uIxFzEMA+TtNWvJ5lR/gDK/MWNcggj5awmW77k6gt9mp13tpWl6eujApjZGCg1uGqOPc2k3GorGDgnOADlo19qN5U2/6hddL4nv7dK8JvlmTD93yk+zPNgQTbv/J+Of41j/IVou1guom0ZdNujWiI=,iv:PfBquSkQKSzTIU/7/O5VmFk5AdiB19o8Z2Wle4ZhJ58=,tag:Rs71QtEGxxvWOZ9rdfHN5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd3hTMkpFY2p5a3BrbXdh
            NXp2dXNFWkdXc0trODIxUzE2bmxmM2tXZUdRCmNDaExkV2hpYjVYbVY5VDc4alV2
            bkFBcVFJSmNlVVpYVmkzemdLUHczL3cKLS0tIDV6MjlCZzcyOXhOMWE2WGZHd2E2
            Sm8wQjRqUWZBdXlaeksrek1NM1VBTjAKVjz5g4HnUzKf4hZ6fa7N3X4h3tA4k2m1
            X3kLuigJRzVWGfYpNWHWFMcYnaVnMIEcQLFFDhnr6TcHTv2uP4T/kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T18:46:28Z"
    mac: ENC[AES256_GCM,data:fumEtfnVkqEN8t2pq0uXaujXS3mBMM3KMrxI93+jaovzKzMIAYiCqAL7z9g/S19DK5qyzQUrTeHP0TwsvEUtDJ8EslM0OEsuBnp5Ksk0rjwe5rfL+RpDlo89LDUnG2NVb6I6d/tK0gSjHRn9jVnTfw+0kMgW3q3VZ+PjcwN5aiI=,iv:VkAofSBIavQXk2bI9Z2xTKBZFo7847TfgH6N/M4ylUc=,tag:icmecLXJa8htMtnlL8AL/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
