apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:NDSNCOs/kuuKWUt8Sl4rFmoMDz2xNkbu16iPkoNwgnTGvSEH,iv:Z8myQ1Wyx+ybLYMDaCYw0zXqPBKydJzdk6Dqp1qEiRE=,tag:b8MatrZn24+9khFIj0oluw==,type:str]
    credentials.json: ENC[AES256_GCM,data:UvNpgsTe6WZhTtLM9tPgmqO5XnwDDjo6bxOie47xP9rR+1h0gx+iTMWYZ16RF3NlNZjgJJzkG6IxKgKeTdq19hsntshm95tnC4rwApIN1p+gLijAl2+S4XD6pqrmb2ZCXOtePiLA/ZQHuxvRnRwzYaBR7p6dCOboohxtNQi6qZMZjDB0Bwo1/z3g6lIbWH3yT6y8e6dqtgLODZzErNIjIN4D4GLrz+pUCTp6T73nIQ==,iv:8MYwItacgjoXsguGPrwtATiyYZO7N4Fdi4kzDOQ18sE=,tag:8QytoGErQR4vVePxsLG4eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSFZOY25MWDlwWkpUWVVF
            SVFGSEVLR2QxZGxHSVJNVGVYTmVtSHJWMFIwCnhtTlhocHplbjBtL3RIM2I4RnNT
            eGVlaVVwdm1Lb1hxQjR6QkVEZUM3UzgKLS0tIHgrTnozeUhzSDRTQ0JvTDNoSkhD
            ek42SHdsRkpVb2lmOEpzdWoyRWdkV3cKXbtoC9A1prDKkSlWUIGdyZMm95akfi7f
            xp52Ui7UtdBhvttC42vSftOVyZKOPXbYSyZ8a/kFC92bhSDST7Rybg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T12:21:35Z"
    mac: ENC[AES256_GCM,data:3LAcuGURY+L7aXCTTF8gBkEGy5whUsZ30k5/4EK9AXw/TZQJIqBIAPZucZTbqcmEWyQclffoQJOEeoIHdy7lT81NHI8nwOdzMb+q1RB9ZRHPW50ACMbmgxhY/EGC2AfOpt+ik69VyBfKmB8Z0RFRFd04FEauu3RImwocf7WaK6c=,iv:/Lpghv6rjWWdUTRAfEnSzUWM9wFEinajKCUsl1B8OH0=,tag:U10d6dTS4OvD/78hJJRmRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
