apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:CpPGFmryAsThf5/V7tNV+aLLQPoIyKOoRdka7lNkQvbPyUYL,iv:pjvBBnIb7XZGfXvZoJ1cnPPx+0KLW5UF4FrVvlrWN8A=,tag:rS3Y+tzUEeFUgNTwDwhVqw==,type:str]
    credentials.json: ENC[AES256_GCM,data:BXn3jCnbfuA3PEn8DDTjV/VWODo99dAIV0GvsF8MFRg2hM96DqUsloRf+ZhIFiLrgSapk+L3xki1GSqzNmGzyjzd4nH6Pnwj4ROniA3oSxRwxG9OlRDLPQwUcSorFmBFSuLWsYVPntLd6/g8ZcaCg4hvYmbvxRhr7CaMy+LtYPmkojLGfRQ3fehMqk2siyETmwT3a2fpXl+ELoPbpHOcMPjzlea7+vumyZVDyfmxIg==,iv:1CCt8VqmV6ICOrZyhuHgkojiI+66aqyKCVny3pgmjNc=,tag:8N5GbPorYkdHsHrodBuELw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS3N4KzBhK1FDb3M5aTRE
            S0ZFeWNKRHE0Rmdoc2c5RzZOTHkvNGZ2SlZJCkpoQUhPYlAySFpCc0dWT3VCTkhz
            VUhtWjNmcGFPeXh3ckZVTGFXenlYWGsKLS0tIE9jQjlyNWRoRzhsMTdGcnZNNUZQ
            dFZFUzk4NTJZd0NZVE5DbkdJNWxmUlEKE6b8xL2jwXJAHtPncmAuWbnsuR8L9WY5
            jGZqsBRb2cLQkBJIN5ErZ7Rp0Hm9EPpqNgdqhxhMdLQxeuF4zlRzcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T12:09:06Z"
    mac: ENC[AES256_GCM,data:DSIa95WRfVSL9dbBzt6MWrrJjlzkZdX8A8iOv3uO2Fs46EHp7CJ7GU3cAPbcTwnlqxl36tWaDckO3MG8VnkMcKoKaymBUWX1SyAqqINO4vhszMo/2a5w4/XBk7IIDyE3/0jj9QTrQHpLbMe7SvuYuynl0WrJVO0zjTqAJpYFXug=,iv:0QspZktRj2TuwBL7HcYsVs9Trhn5uEuG4MaIz1SeWYU=,tag:fKfFaKgelbA8sQWX9GcKPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
