apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:j7JhjNYUgs5rBe6MwrttOXyjG59vR0E1F5h9gm/KDeY1gLQI,iv:jwCLzKoEEFay++NHRZ7I4ZaoGlx5KSk2AWOO7lbeZpI=,tag:VURSsXlaoEQ6kavUrq6nCA==,type:str]
    credentials.json: ENC[AES256_GCM,data:1E3xDrZH2voDl94RYjgNJETYNc8kYmGB3AeJvQTisSlA2cfPytSI2cUMaLtmzghRDfyisQtCMz1fBRiHnNnLOVidi0NYHfvuMp4TEQfzsSjl9dCRRUQfINbKGR3d26NJFgK3mEVk+1A7xNrHmzkqg7AzQC4XazrMOdUuTSHc3Rl1ltliBZguQagyQWd29VGhpqtHQOreCidtOls427HMrjTM3vN8xka0LvNpG57M2g==,iv:2D1OCW3Ctt/Si94Q5LXVm2UgbBs5HFUtmuV+x6HpcUc=,tag:p9ARDpr52mlKZ2qhNMYzdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRzUwMmhZM0hRZ1FhNkhv
            TVduYnJMclNCcUZXZDF0cEZiNkFpVFZucHk4CnFwNkxXQ0JqWG11ektnRzNZVjF3
            VmdFbzdFWk9oQWVFRmFyNFZXY0ZGY3cKLS0tIEF6ZWhQQnNFTkRacmJRS0M1TkhJ
            d3FXVFVkQ0E5ejFoTlN1Q3JJbGNORHcK+h0chx3dY1WQZYwOjWrQj3r4WDMsM/PO
            BY5D1APfacJhBxydqKhcbCNLohxfoFurJ8Tf/S2td4elK+sO7CeoTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T11:01:20Z"
    mac: ENC[AES256_GCM,data:c9gByoMrtyr47INNU8b8ui/G34YTKRaQR9TrHDISUPHXbVo7nW1ue4IUdwHV+a1zDt9yO8yz7P9t//+nmq2/ddvGW5dkQwLv5P6F3RC2W8CuSj0sIdl54hhVY0yEZqjMxKL6fcwxLp+Q4XXjnl2cUi59rwILFlUxXCiwy5nVPaI=,iv:UAJj7Ff5SFWSkUXyHOSIYs04+K0ANAew+9h9oN31klA=,tag:RUqJStUHosCCfaX7zVl3GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
