apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:46uiT49d1tL9JF579/dRlYdD0B0tXOTEZ6XjsNs4un8CUX35,iv:HI1Ay6tba0/YdclY+IXqkxkWR0hgl+a+0lsDJUCbFIc=,tag:Nm/zaOqvfojtbOfIEd8iNg==,type:str]
    credentials.json: ENC[AES256_GCM,data:88deyami6APztEwNyxttye+Yz5PXM2eVP92f4F4yzNQRWrVsUQ1xlhF1XcnhOLLEKco09wW2c2asfe8DSLDgVhovhRy4zdaT80yXbeNpiqwv/PgUXKWIOeNJfmOgmMda8hm6elLHIpE/kmutalTr3vHJQLi+MnJ7YbRS3n5tA4eJzOXftZGT8qGcpUep08FGAo7Wf+qQozuuCg3TqQr5nFPr4JLAnWfGTc3+RMhGTw==,iv:lhIaVx64Rv3b6BNwZezJACNmLyMcgHVpIqyXAIm6Z1w=,tag:3e9/++lJxHcUIfL+KQwIAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYnhxdTNxVkRVd21LbkJn
            QkN3c3ZHYitWK1Z2eEFsbVhpQVR0Z3d2bmdvCkFhTTR5OTJ4UFJRMFBJMlYrZHg5
            cnBvcit0N3ZEVjZtZVZISjFXVjdPdEUKLS0tIGpZRDJyL0dYYk1kbWRWYUdzSWh6
            QzR2SGk5dXNBdUVTNnpkR21iZ1owbHMKe6cs+QS2qsT9NgSB9pwT2Tyk47Hrz4tK
            wLSJ4t8O/DmyqTXLigCk8cFTS7VTKixCjsINtfohU3CSI9IdATyunA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T21:09:29Z"
    mac: ENC[AES256_GCM,data:lmLzIfGdVqOSZglExJCXxAe5BUuVGEAo1TkMO2TQC1IMiOTZo778aEbPa+OrizpIwQ3SRLnQgKTy+O3QuG5jmKrWtXO6KCLNDdBqaoxzlOb7e14ON4NS7Y22AJbYnLgt3B60qXFVzJdp/oQUnqsgkR+wIZGjitWowHrcaxcrXwI=,iv:KOxGuiQFDGU8JdLHIx0REwwMMOtC2K4W7EX5oAEqLls=,tag:NK/JdLRAAaMzIVvC1DNR3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
