apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:K/xnxibe42bPe6reKrDTHO+/0Gvq5YZJWSh3YsvVjHmPZv9j,iv:Q3aMijsSYy3IDiDs9XgVWY4JFj1WvmEvWv4FJf2dWi8=,tag:8cieNZnEOizGslHzuQ7RZg==,type:str]
    credentials.json: ENC[AES256_GCM,data:Cl01tVLEajqBKZ2cJbSqOaE+dZZ3tC1uoJWEKO6ztLb2e9TvZ3TBsEpn0SmFbTqkN1117znJwFMODwXDqFlLoPGTWwPuJqD8ICrsGho0Jcaen7u3XQc7yYDaanCB3GKSPMeMaaPY22xC3m7X06EJmcqIHJAX0be9KIr03hRbS0YWhfRkUVOjAdJdmJlnyIXPWOwWcXpyVD3tp+1AP2f+Rs1x8ln1eqMfnDv1hrc4QA==,iv:b1fR61sEhMH5189c0y3KnZ/QByFvdb9tcRC0Z05JOLE=,tag:PIf2CvXr2aGv3R5+8o4rZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNjkxc2FPbFUrZ25lNjRz
            aVQrRFpTbjZRTEE4dk43YVZROWUzWDAvMlJjCkpFc01jVnlaWC92SXVhZjd4VlZy
            cjE0Rm82L0wrbXFCTExwZzFRSWg0dEkKLS0tIE43ZmxMcVZDQm53aktpaE9RT3gw
            bVFyZ0NwY1FqV1ZvUWd4WlI2eUJwOFkKk/iBdzjiID++4YitXsVGMt8BAeCt+zIm
            0Y6XyiVjyln7uiBEZQL13e15nPZIj0h6YokInUHuJO/2y5EYmdifUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T10:23:06Z"
    mac: ENC[AES256_GCM,data:wiYYfGR4OKXIYMiG3OHSRYsb/Y30yOS9Itm4mBIDEtjLzVDcikZwWJ46mJezdU0I1/1yYvCcl7mn0Pk2/Fr45BiVk0Fh0L3EiTTKCr6lr4aHVn/55qWmtakQrRHppofdFOQf28JXzPsoFQALsenxl/oNeTTIxHaS2xkYzW+HiWY=,iv:YvBnDypDheaCL6OMTBUNhpzjmIvCfnA1Hdck3wADb6I=,tag:1jwW+buqXB4fhpxpIkgRYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
