apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:z6RvjJqVgK7rlyITRHUEvkD/gdBr5Ih0xDdOFogc7Sw9sulO,iv:h2BAC01OWRRrZJZ6d/rafIzMho+wfFJezAmFkB5Cy8o=,tag:zDcpXbnCMB4WME4ffM3RZQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:OkTu3FWJbBtRjN9zqCaAa38esuGVGVNok4Xx0hBOLiCiIEZQgc5U5ANXqRMdRnXGWzX4XQatqdGdIUm2oEdvqO4hOQr3lIPDrNmg5tk1JrOqhpMEk0lWirbZ3QBiaNkSLxob/2MlWWsMBhuMU1pWhzQ9lcrOhbEcHvgCM4R4W58ZNsQ3RRguyYPTbXf2xXgfITyx/r9TQV44aDIaKYtqAJksah3XfIOVIhaltxwjzA==,iv:LxQflSXDNQUTr9NMYgnUGRbeKOJz8oSA8blxExSMNCs=,tag:g7/1cruY+KRdgRpXsLGNjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdEpvL0x4cVRkaUtjOVM3
            eiszZmg3OGFZYTI5cUVsR0QzbjY0K2xNdFhzClVDYmpWL24rZlltSis4SWp4MXll
            M2hRc2lmcUpFY2htbkt1N1U0eU55RkEKLS0tIGNzU1FwSTJUdHk5TnNGMUZkNVdl
            R0M2UG0vR3I5aW53M0IwbFZ6dEZqSDgKO21felCSdsFjcdirf4yP86cP5EpHw1rf
            no9dCmuBJj34GO5YHOmLWZ8V/pduohn2Q8v9ZrhXFGhbLr64G/PQfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T10:29:03Z"
    mac: ENC[AES256_GCM,data:vcgF2xk++QujTteaX1YRaGBOeRL9xz8dlZae/NuQVyj46HoxYJXBhQQalSk9cHK4uZJkTt7jUwYbIFMqTd9/PU65aADC4MC7Q14mDM4kBFM8wRmUl82jCiDGGZbikAl+tm6iJGgys5+TMQ0GBheMgJ08xVoBMCTVLhe8W935sf8=,iv:Ni3OEEISzddS4HKzIiqKtTanFyUgKJJL5Gp6EloFiQU=,tag:zbSU8A1AIZ3umfvEcyNo8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
