---
csi-driver-nfs:
  controller:
    runOnControlPlane: false
    replicas: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
                matchLabels:
                  app: csi-nfs-controller
  storageClass:
    create: false
storageClass:
  nfs-csi:
    provisioner: nfs.csi.k8s.io
    annotations:
      storageclass.kubernetes.io/is-default-class: ""
    enabled: true
    parameters:
      server: 
      share: 
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
