---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: v1.7.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    longhorn:
      persistence:
        defaultClass: False
      preUpgradeChecker:
        jobEnabled: false
      defaultSettings:
        defaultReplicaCount: 2
