apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "${CLUSTER_ISSUER}"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: "${CLUSTER_ISSUER}"
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"



