apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ShMNLfoiMhIfBDm46d+hDAsJX3QPzbhjiU9IsPj4LV4Bpa9zWVD60g==,iv:jfFTr9T8aHZ06x7/G7VR/CzU/zS14qO6O46k/o6H9Nk=,tag:JeKskh3krOI2nyrGx+ZlaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRFgwV2UzQXYrcG1oRnZF
            bDRHVjI0WHNmZUp3WG5lZ3kyak9qTkRuUVZrCnE1OGdLMzFibGowZFN4V2tQT2hi
            YmN6cEdUL0cvb0s2bDR2WFpVUU53ZU0KLS0tIFR5RXJCQndmQTRhSlhVQ2dUb0Yr
            MitXbWVsaG5ESDU3Y2tTUHN0bkRLSHcKqhsw+LngbqGa5M34n4ZcR79fhiEg2/yg
            ejNSJ/9E54CAO6UwANB4ho6FPSk0hzOk7NgrGj/AqbPXfd+8/uwtMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T19:31:41Z"
    mac: ENC[AES256_GCM,data:mtFrkukzdLYZPzrZCnP/cNMayftAFu7TRxLgdEdCdq5XJz++vtGcxWte9Z/gzSCgcWOYcgUt1JRM3D0LZnSATUrkJOAveZCWFV8kVjofwY1Wdq2Df0uQTER2lsOd+KKL3c8p08iUynZTZBVUKQ0N1A69D72cZ9GzVHuBgj33RQQ=,iv:TbL7/6KOe8ZMehIFro0rV5Ecee9pI+GSTmEENqff1xo=,tag:GKm4f8eSwLaJDmkKbIuYMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
