apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:f6UPhp224A5yOAFGCuIpbsLZ9vmfY/SZ3j0quF5gJrvXFdRO1Gf3tw==,iv:77eiC639yQXolwUc/zMQPUlrp/tdUb721Qn09BsBG34=,tag:Y5K2OdYoakWLktLWYsTWug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q2o1RHBHOHdWa3NsUVRB
            S28raDNlRkJiZmQrdlR3Vko0Z3JnSTdsa2xrCjNta3J6dU55UzdFYzUwalh0NjNy
            YzVQaFZPaVAxMVorbGY1WUVacnROOHMKLS0tIEhkbXhKaDRsYVoyUlBHYUNqNzhm
            WGI2aGdnNkIwMDFHdmNGNHhKU3NrUmMKX1EFqYSykmOtKyOw7h+wtpa5t8Sb1TkL
            yHm76IgIYk35bQivqh1TmjnVwjWsW2D4+whbUyTYXNZUFZQ1xvBYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T19:32:45Z"
    mac: ENC[AES256_GCM,data:ErAR5VdVkzi3bcO2o6SCtJvzT5MIr927Ffe8PxiaLe0P7zK6+JO4c52P5M0MwqNBLRSDmQ2WBuIvfxGoE58wY+zwVk/HbmVyhPJOcoGmnFDqAvoUWEk0n5eJ39c3SrxPGO5XDwov/HAAK5aMfCOhrmei5AQ6ulJm9seuaFO4qIA=,iv:s7U9E78a1VLUfc/t/srxsc/qGRrZPyDE0yjq6mYaVg0=,tag:cYnfSuxp0nLAVChFCDUa9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
