apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:EyhvRakE5gPX234zwzyWTiJf0QLsBdYprgpvW7lzo7Wn+q4OFwPjjQ==,iv:BQgFDjNFHxPN6OFX3USBP4NfGWS1PP/rvU97o8o/1E0=,tag:49rT+T+2FHm41dv9OnPbYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMjQ1V2RXQUc1Y3Bpb3Nn
            NVg0Yjl4ckYrM1dWMWpTREtkOHgrOHJOclFnCnB5d1I0UUluWWYrZ1NCV2VIblRs
            VERHZ2w2SU9jZmdLc3EzTlZRL3FsbGMKLS0tIEk3NFN6U1h2ckJPQ1Z2VmVheVhw
            YUo5TTlNczBpejliQUZuY0F0S1UzNEEK3xEPt1xVNl8XzeLG42CkxIzO/0hDLG3H
            qwDaSbS07axQTNBLGphYWeJD/cSotneY/kQMN09Wlp9sn/0YLmbYxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T21:26:32Z"
    mac: ENC[AES256_GCM,data:jM6FOKZhEmvDaI+euwlqK3EXKTgsW2VgTYNcpEDZQGqStPEcAupvGc8Vvqjy61w/HCrI5oprl+gZRNmS7fk9E1K/IQFTGzkLil4aITTa9LD250xox2Ept/nMyIcI4XiKUyVAZzGIGMpd1xC/x4Z48WlYUEYGDZ7h/AuTZNNu13c=,iv:tAuyqtemB8YTnK2YGr9iS4FGAL6KA4ZCVyy2SjdDcw8=,tag:w9VntRT4Lqq5OOsoWi2Xyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
