apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:I+MroGp5IhHL5f72u9kT85eLZ2wgrPPv5494EUDaHBVn3GZVcZLXaQ==,iv:NAwTL2hzRaPTpPSQ21uBdfd6daCS0pS4ebnTRKYfqo4=,tag:DWf4Ndt+BG+3ABDHuoTqcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic05DRmdCY2s3dkwxNFgz
            Rm01TlJPZ3kzTlVkb2FFbWx3UzZRYTE4SjE4CkJ6TEp1Ukg0eUJWTGMweXBjb2Jt
            VzN0eWRUUUNEQllzQVpScStlOXJ5bVkKLS0tIGJua04xenVxaXhKZjE1SzR5U0xP
            WWZCbmJHQXhzSUJMeSt0UEZPaDZTNjgKWKD0Y8lCuC/iDOHSlkGlON3wa1RWQmJ1
            O4zPDuJCWlvpbJwy/XGNNCiC2ocN6Wl36g7fxRfA0DO2101ip3VW0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T12:09:06Z"
    mac: ENC[AES256_GCM,data:nEYQ9YdT+7AAc+vnlq/0922E5o/1nKr0ay8PgZuKq8ivM3TLeX5L7ssvSLfc+cc1da6CVAuRQyMcqE6MZV0IE5eggdMlsqotIoNYGU02m4qwhG+hw2HZl5ba2qwMV2EQoSVVvJ0QkzQj/Q1UCRg6xZRc5W353q/ERjX17PBc2Pc=,iv:qFlKQ2ZLMF4JyBShtXzNO6yVRR12DsGjrcuZRh7SJKM=,tag:Bi4+aZoDr7ydFWQFBsl4Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
