apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:VcDRjznXxdheV5ES4u3hvnH9TzSQ/uoJ0qA2oICd9vPzmhDWTC7VGg==,iv:k9z5V0zPDOsc4iIivtciEgxkiSyPf2JoizbQfrl97g8=,tag:6o4EjTLVT8hS+QHOrdqDmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZjFHcFo0SFVlc1JtRWJB
            RC8wdzU2OHNhSGFuVjBNSmZHWldyRGVNYjNzClJMMWV2dDBpZGREc2JGUHZpekU4
            Y2taUGxkOWZNazFIWUFtSFFXU3RtcHcKLS0tIHcrR2RhWDlKYkNjMVI3Wis1TGts
            RWViTzFkc0JZdTRpTnVXNnV2dkJhV1kKdfyCUDgiz1eneJG8tHFWyJhIRQ9ECO4Q
            rRN63CvR/4bRWCBPFJpiuMV6KCMnqSy9JQ+K8bHAwBBSgqfPvEk5YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T18:06:14Z"
    mac: ENC[AES256_GCM,data:4YAdReSgZQHE+qrThuFhMGhPeAFpS7EBsY0wTUd8D+j15bCtTnt9DUgUy1LNQGNWTUlUcV4RiQtbQhAH9ia5VJKRrolTmGOxGuOzmZ/RKezZpiejO0BzJBIbf1QnR+pEgi9QzYK5FyZJWqnWzsyrTVu6ngnMbOTMSrt5byfpTCM=,iv:VE3f57rt7n/suK/sz7TkwNVMTOQTeC3ACkSLQQAHfj4=,tag:n/Mo3X5uauHMwRwU5YOMpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
