apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:GepvAUu5Nypd63WSzqW4U0fXuUmwmiLUXP10lutShjp9c3AWAOubYg==,iv:3Wx0c9XVaY4opZpFOfUWBbAIN+a0bRM1LGIMF5cK2vg=,tag:VRr3nzGp3kZcqroJpW8J9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRzlWMUFHRGlTUlRIRDF0
            ckQ3NjRDVTZoMjlFNVJxT201UUY5dmt3aFJ3CmJ1Mm5XM2hOL25iSElTQUF5SVlI
            ZGhQTFUxbk90Q1VBeWJwWVBZRGFVMUEKLS0tIGp5UHVZYm82bVJTM2R1NDkrVTlZ
            Z0szQ3RPaDRkRkNNYklyeEZXRHVXNFkKIRq6iIlK1Y5bZojVeIFgq5vAGTR30V0f
            /oTSD4zAbOdZxezz3BYZCp19qczJgYfH05z+RfCe57s6PrndGstBcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T11:01:20Z"
    mac: ENC[AES256_GCM,data:k3ie4zroj2xsVKw+NveaLdjDypvgTQ2D4XkVlvXpQKt+u0pLlbmW/qu2xxcPPgz6IycC6xaICSWLseezS22yG6PQnNL0yt1eV/uIRS75A7Dc+FWKlgt5epyMoLfIX2By5sJYt/2D/gQanTLYSS1M7n7wk9MyWU0xMaP3qtCTep4=,iv:jP/auXde7XxAhfhWIHrTobf2rWZMetS0UqR9ujncVNA=,tag:pYajPX6yWwGBr6SRy6gzVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
