apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:pvgdPo2fZpdTEApOaNzOiXHysUTOWSpKy9+Zif7vikX2bQDdYLL/pw==,iv:0IF8Grlz7/8vO9wDN0X9b9MkuQxX6+xecGVnBkeUDYo=,tag:7aEra+lZFfYPOGhD0gIyxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHh3cjFUZlNyajNEVTE4
            a3d3S1c5VmN6T3labzFQVmVRZWVCSmtFa1FrCnlub3VsbU02dVhEeFVoNjlQaGIy
            Rzl4OEFPeHZrTW1kRmJTbUNQNWhhZ1kKLS0tIEl0eFZTOVZ6dzI1RWxINzJCcTdK
            YWVFM294TlZoL1dRSFBhYmpYTHlBSUUKaVHGglI+mtxdNElD61TWQkr7/z5FUwL1
            GQe2kNX6BC02l+iHS7z1gVK5UQPAjGdF8bWJ2Krdc4sZiCpyMq2G7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T11:06:49Z"
    mac: ENC[AES256_GCM,data:ZfbXh97AJJaZh8kL+axrIlco0weogvQyA/b0tWwy9Bp3snQLG96HBzZ70gujmxrjHHNdIS8L81PlZD30soalMNBcw17zjO7rtYRJWFRJwT0bbemEPuAQQPlLx0f7lMA1CYDQ24yG/ug+vQJJFskRGb+PeQjvyk4kgfTBlT7qt74=,iv:NgXBFa4HPt2l0ILZqQ43OYUbOiCKzwXClRRAqrZDOyM=,tag:t7EVBO6QkIRJSOPFLgZt2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
