apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:6sQ4t0qF4W2mMs3ogjX4b9Uzd5U3Yn/Y4ZSzPSPZHB1BsCI9nWoQ6Q==,iv:n8PU/2CHvXSoKZrWFhfpOhsqIiqKnINfCM1ODsh9kLc=,tag:iwO7YzBR00UJIrigFAPS1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MUptWjhRRVlXbzlnVEl4
            K1hvTVpFOFBlcFJUUTFiMEpja21PTlFDRkYwCkVwdWNVMEc5WmRjSzVONG1yWTVM
            VytpQXQ3TE5uNnZyQjg2VjBXRlR0TzQKLS0tIEpWWlB3WU95ZGptaWMxQ1hxSWth
            MW9qc0JZb25veGpnUFdwZHoxUGE2WWsKTK6ytF5bfUUosiwK5DJl3RgjTF/u4XCg
            7VFVQIW/0er9xlNbWugQhJK73t9IEdFWxfSxGJefiZMMvO9NebfrIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T13:26:04Z"
    mac: ENC[AES256_GCM,data:IHQH8ih0ss9HM2LntMwzfoalMNE6zcsRCzsHG/7bH1jT2RBoMBvg2pmO4WCLm9OVEXAsAmNcijpIIRdo6mzBhCaMThkk0z5XjGJ33YmsVseaDhuWHjcOHB//B/1dEO2ZQLUyeNlw+XEPtjrrlexRCPksKNloa4Oo8r8mcVcINoA=,iv:93NNfE41saLkB8erRumNcpExBYi/EGPRaSCTmNjGpcI=,tag:BICDOxPxIlF1JbvR6ca0Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
