apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:jAbv/vbyUN/z6iCmPcv1v4nemleNk3noRIqIWczb8FZnMnsgne85Ig==,iv:EEUFHQ+xBKke3ym4ghR1FdrSSc5TQQxoWsdfmWLnPMo=,tag:eh895sDHgSuVI79D7B51Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcm43MEtoV0cxSFh4aExF
            VUZnN0NwczJmaFRmR1NET0FYc0tXVmVyVHhVCkJBY0h2QUpYQW1Mc1pPdVRGWUMz
            RGRXak1JRTNrZHV0bVl5alhhTnR4SFUKLS0tIDNTUzVteUJweXZMZDZMcmgxQnRv
            RWNOeERoUG5VWEZuMU1xUGlhek1CZGsKaTjVCJOU2vR+gHZpoo6bfYhEzirMKrUm
            ZVyEtWGPJnLQmMGTPChiUgD49UnswTC1XWEgq6osH4y/aF/9lrmBzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T14:12:33Z"
    mac: ENC[AES256_GCM,data:jvzF6MWPDosVoI29IkbOjhRP0Y+YvqqOCWjEiWobnF/vabJgvG+7iQCc4NHM0HFDuwmV+JAWTwpnArqei4GUQLkM+rDklmXmFb3nzGPw84TiBuRktw0RC8p6yU7uvDmjh6FaJuUKortSGGnrlhM8gNsPzaMFbb0cXKJ4i4aQ8bU=,iv:fVrO54MKQdDiH+grSgxAeFWRMSBf0M3olW3jE2DgKUg=,tag:9EGv5C3fJwnjwnt0C9shNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
