---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  interval: 30m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PROVIDER_REGEX: ^(black|cloud-arm-1|cloud-arm-2|white|n100|datto-1|datto-2|nuc)$
