---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crds
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik-crds
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 29.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: traefik-crds
  values:
    rbac:
  main:
    enabled: true
    primary: true
    clusterWide: true
    rules:
        main:
          enabled: true
          primary: true
          clusterWide: true
          rules:
            - apiGroups:
                - ""
              resources:
                - services
                - endpoints
                - secrets
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
                - ingressclasses
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses/status
              verbs:
                - update
            - apiGroups:
                - traefik.containo.us
                - traefik.io
              resources:
                - middlewares
                - middlewaretcps
                - ingressroutes
                - traefikservices
                - ingressroutetcps
                - ingressrouteudps
                - tlsoptions
                - tlsstores
                - serverstransports
                - serverstransporttcps
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - discovery.k8s.io
              resources:
                - endpointslices
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - gatewayclasses
                - gateways
                - httproutes
                - tcproutes
                - tlsroutes
                - referencegrants
              verbs:
                - get
                - list
                - watch
            - resources:
                - namespaces
              verbs:
                - get
                - list
                - watch
    metrics:
      main:
        enabled: true
    additionalArguments:
      #- "--experimental.plugins.bouncer.moduleName=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      #- "--experimental.plugins.bouncer.version=v1.1.16"
      - "--providers.kubernetesgateway.experimentalchannel=true"
    # persistence:
    #   crowdsec-bouncer-tls:
    #     enabled: true
    #     type: secret
    #     objectName: crowdsec-crowdsec-bouncer-tls
    #     mountPath: /etc/traefik/crowdsec-certs/
    #     expandObjectName: true
    middlewares:
      customRequestHeaders:
      - name: websocket-fix
        headers:
        - name: X-Forwarded-Proto
          value: "https"
      forwardAuth:
      - name: authentik
        address: https://authentik-authentik-proxy.authentik.svc.cluster.local:10228/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
            - X-authentik-username
            - X-authentik-groups
            - X-authentik-email
            - X-authentik-name
            - X-authentik-uid
            - X-authentik-jwt
            - X-authentik-meta-jwks
            - X-authentik-meta-outpost
            - X-authentik-meta-provider
            - X-authentik-meta-app
            - X-authentik-meta-version
    service:
      main:
        type: ClusterIP
      tcp:
        ports:
          ldap:
            enabled: true
            port: 389
            targetPort: 389
            protocol: tcp
            forwardedHeaders:
              enabled: false
            tls:
              enabled: false
          ldaps:
            enabled: true
            port: 636
            targetPort: 636
            protocol: tcp
            forwardedHeaders:
              enabled: false
            tls:
              enabled: false
    ingress:
      main:
        enabled: false

