apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EAMo7pLJyncm,iv:QG2QrLvSa6IWQYsFea2rdTXourh7zLRwvLI2MaGxCoM=,tag:58NaX9qakjY58+tjZCdALw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eWZDmFiJbykN9ThaSaRl,iv:HgeSAfyPohUCfRPBlvRM1RrtoUXo5Dj0dA2nAiqEHq8=,tag:Eh2IJ/+n/ds9QeTW4vXpCA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:x7sMy9CktWV4du7RFuj1rCKMw230kWKyQGTSkFbygFT1s0Bj,iv:dlgXwpGtQklmVoLcZOjgoJv/To5k4Z7UIbuCt6mo83U=,tag:NkXPwpuWvHqwASVosMO/tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiclZCN0FZYzNUTlJDOEw0
            V1NDNVp3U2VlUmJGY25OUUsxMDFOaHFqVm1vCld4VFFaSDNndTR0WGx4UkY4SXpw
            M1FjTzNjUkVKNERWSzZWZlhqWnJ4RXcKLS0tIElObUxPWGlCSFJZSVUyR2xTZGlu
            REk3U1hFeW9qYXArSTRXQnVmelFHRmsKeqC1+M9k7NvFU75xczdA7bcRcDtFlrgP
            BbuWrTY+EmdNd7zZf/CNLUAeMXdEUjkXyyIPxZ2Wqsc5Vt7KSh+lFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T19:32:45Z"
    mac: ENC[AES256_GCM,data:5jtxHHkYO3Rf0EnuimIrJrBLQBWwbz19htK6GUiDOqxLSv714bVBdZgNCgyNDN6b1KxSOQ+vXDWE9e0WjwnSDmxgm8w4F197hvKn8ZSCqIhFRjgU139Ynb2h8ciz664GW2jAQQCA8gayMwyq+8+RmaPt/IB7pVz6hbMwAJ6MtL4=,iv:grU3qrpKeEQRxa4KLEi87iEAT04U7KTdI8VJi6YI4LA=,tag:pOCgUiMWEtedJc+kF7VH6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
