apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Xyl2v5iq9grm,iv:j3I4dytP9wF/fy22nBZfHozXvZHRptrAeDDA0+R1lCQ=,tag:MklWOYiVsuMYAO55u8aOGg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MO8Qi3wQZxGBgyQKGhbt,iv:MzinKY28sTNsv09JYuCIIz5ZUSOwpc2xdB9ILic7DeE=,tag:pnyYphEa+8s0L+AnbxaOCA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Iw/dBg2OheJnnQU7PIEkssjTyoFK3XRnf2uK1xApMhvekKuZ,iv:MZ6Do5QgSI+lJESX3XD1NWhJVefMEbL5zCSfPN2tfcE=,tag:ldETATuZXUsWRSmDTU+s1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bkxPUjRvYmw1eXl0bWJV
            RkhYL1BZN2xJdmZLbDBQcmVRcWtnaVMvc3owCk51YzBZUDR5UWtwa0hvL095VXBx
            SENscVAwWVNwcEg3a3BQMWF2OWI5K28KLS0tIEZLcE15Q3lYN0VxNjhwSStkUGVE
            dWFpRDh4R3p0Ry9ZVGNXKzdjQ3FuZW8KWJV31ahhjYeMV2heElX+OB9voQdNBjh3
            2yiZTPsuDeyH7Rh3VN+gKo36aF4qVUYL+VFejvLHuZCRyI4QRg/8Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T20:41:07Z"
    mac: ENC[AES256_GCM,data:wQcZj6x76QAB/IPLshKS9+zshYyNakCV87lqB4gLLaFXf7XZgAEmQ2xkyo+lEdbtX52KwRvV/L7TMCO+sim98Olr50y64/JXfSsUT2R1Rk7Ktw2lp8lhyLfwb4EfgX7HH1x7S6dK6G3mMaAd8jBT8vyu+myuL2dX9zQOaBwn3L8=,iv:15cXGkXlzTqt3iqZet5KnHKxxKXBFtToJAn2oT38PMM=,tag:VUPVUqhZ+IPOQn+C0mzoxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
