apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wn04x++S6Rr+,iv:ZLsSxv3VsLpdfedlMhde65kbuUoRnrM2ihjLuTv+TeE=,tag:MSW3rLR7HZjlT+EOM2NV9g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qYuIXhCNhZ5/XwpFLgH0,iv:5UuUiJsDiZfkfRseUAgx8UDr+uuvEWtQwKaBwzYjYkQ=,tag:chLMN+cVD4TsPo5ZLTgpMA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:WHgVo8h0IraKVq6x/1mdOrCC1mLR80AKotPqdNF9dCo+eNrC,iv:K9uKIJe35kmLBK9hmwHKFf1DFDUcOJfj0WyjtwgaF20=,tag:sVJnjaE4sY8HEeboFXFKHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySzFhLzlYU0ptOUtMd0FE
            dTR6ajdiOGVyRHpGYjJyaGF2ZHpLZlJFa1dFClJvRVhPUEVIZzJxbC92SDQwQ2Zl
            MGJReVdOMXBGZnI5T293SlRyRCt5SWsKLS0tIDB3bldCUG1lc3ZnT3gvYlhYNC8v
            dmJaMi9VNlZUeXBIUE5udVhxeHVwVzQKOSsQVhmIDC0uM1bsPK9bHXi4PnwHJ2c6
            pNedsrlWhJ1pG93G8KmEoZKJbmx1wQdCta4TCvT4o0sA/Fj0gnjDAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T20:22:54Z"
    mac: ENC[AES256_GCM,data:GVFPm6crSUBWrCoA436XhJ/4Vfty1v0XIzD9DYONt3nsH149Yc+NsqV+MgDN3Szhspy7eqE33IGenrfzkfR9AC6u2BrOHTa+zwMqXrEfudWJNO16lU2AygZzGr2LQcMgBsqiE52qVD4S7fi45xF0s5j+El0wZhnjuI+1ogAa73I=,iv:FDht0pIdGmEw+cqxPepq4buUqj3v5EVHipSW1tjeXAg=,tag:Hy09UCAV/RVHPF/CYODi5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
