apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Wt/Hlz8NAxFl,iv:uQZAZFgFDAg6lgktfrK52iWYTW7RRpZdTWE94+C5sb4=,tag:li5cjLKh4qRy5x987ubGGA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FfSROETWCcZumR7DaA9e,iv:oRn6TNed43Utws1lhQD6T+vCfuiMw3lvX3dxagqflBc=,tag:cczSpBSPg330PB+1UE798Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:GAao2YZn1utxokJeXEbZ+CFpeAXKy4QICs+LECcj3L//+v0i,iv:tkDxAyCaSOX7E81RgPiwciJjaZ/cbdknflGfgA8dHPI=,tag:9VdUk2fnU7hA31kara9xiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJajJUc056ZWpza1JkekEr
            RkZVRDBRenVJbFZibXBPd21FcXdLUUM1ZkJvCnVXQ2swQjRHQTQyaUFLMXJHTmE3
            Z3dpeDFaazZJQlJiVFEwQkpxdEtrZTAKLS0tIDczcXFxYmZYT0VKeTlUOUdIclkw
            Sy9XM3ByeElTcEYwVWZGWlNRTHhGN2cKr+7EBWjX+eO1GcOqPV4aD1JRSHPkRct9
            p/KS/zILDZY9lL3lDCY/+/R1u4nBZWL5Y1IVxg+jLnDxiqCKVGg91w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T17:24:24Z"
    mac: ENC[AES256_GCM,data:QWVzkuz6T4ChVWZ2lMYx1Aga5gKriXPyhuLPTT0Vo1KYE3uWbw8Xi54BP/Mozz6eq5EyfTXhgDaLWPs02W5L+gkgWTKHZQaYWw/sfq79nLd6NuTMlzOzHeeFtAhkBT9bs5YzauGZ314PS2ejWm89bKstHRaQ2708v68g60UXWIM=,iv:JVyUJGBNl/EPS8Mpz5CXelHVFI8rXZ0BifdMoEU6Kio=,tag:VyTrh9JvqWCYMUPNx4KBnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
