apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:RvkNaJ7cEHh5,iv:fxg7wuRXB4KkWiA6QrkDr+Wb8TO8sAuEt65uvyJt2Jg=,tag:lsruaLlA6vCwIgNs+zrhNQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sCsfn4xeguJJMSrHxz1W,iv:QpVf8Q3p2lXPUuo4M/Ikags1POH9k256DzKPkjZ6phU=,tag:6kxbp59LPN+5SMuSoL18wQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:8JRibtVPGpg6Vud7eQvWIKbUejI1ZHbjVCNdsccPBzpNAYFP,iv:ynSWOkdR3Yzukhzx/Rx9QWiydqVe3lo5u920vcUFhR8=,tag:yjj6QEo7vDtahb5uHXqEyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vkoxd0V4bDNDeWJ5SjlT
            YVZLRHRib0dJb1I3WS8xVTVUOTA3VjY0S1NRCnlZK2VQNGlsR01uUVE0ZFQrRVBI
            bm9PSmtWZG5jTlllcXUyczI2TnoyMG8KLS0tIHp5QUswVExTQzhVSzhIVU9KaTNT
            aExTdlROV0RzSjJYSElMeVZNZG9HQzQKWubjfkigKVAynmcq1fD/E1r9fxPXNNJ2
            ZidzF4BL+kiLeS97hxsEq533XbMbrOpVsIrD3mekJKoWu/nfvvCkgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T19:35:31Z"
    mac: ENC[AES256_GCM,data:aoKYPILzucet40EKfq35KvgfHGY0YkYwD0iXK6Ai01UP/HQkIcwJfV/ESc4Met7uq2NA6ep3LA8rBlV6wNvID3tiBPKrzUzdAc0vvIC5O4tPYGpvTOkPk1zzFnmWuG1RNg0pS4/lZqT63UXjjq+UtBuNa3v/hh00JhLlYdMuhlQ=,iv:omeT2g2IwewhQJileNcVMLcIUabCyTFUqe3WIrkAjGs=,tag:zMEbKgz6zscfL/XSHcb/fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
