apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:e52h0VNPjnPz,iv:33BahnYp+oaIeddPNKnyegtvs4vs4SA/nrwFw0WV77M=,tag:baKXf/Q7gKsarL4aoZIsug==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IA0iuaUOoLxSEldXF9NM,iv:7audqIoqjJMWpfh9yQYNcjeuOJ5wiUGjboWkTPxL+Z8=,tag:QFHelcdnVMxRhR+IMgUwmA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/vXcm6wY0BQQafoiKqYhz+7pFC10mUKf1wljentCbUedlPm1,iv:4x7Hy99sQt8QiUbjmmW1e9jj5Yzq5eopgIjaYbYAFTY=,tag:YRro4h1kwx8T9GNF2ywMUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc3FmaGhJMFBoL1lFTkNu
            azJnbDFlK2JmNDhmWC9Dc0xDZjZ5TkloMXdRCnhSTVZjRGhZYWIyTnZ0bDUrQjBV
            NVl6Tmh3MmFlbG14WWYreFlaNTZwZFUKLS0tIGEyWEl5cFBNK0Z0Vkl3MkZ5YnVU
            ZDZUMDZvV3NSSWlQNGNuL2xpbUtFSlkK7xd8IsCmPH6fCCNeYkTCPHer7f4kPDTF
            X3PD9CzP3/1LwyYGq/6wJ1mKBYmG5ZNRjrLEA3GIjg7w6Va3DjG52w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T10:29:03Z"
    mac: ENC[AES256_GCM,data:i3nSAaO49w1BaIGd62Qnxyf91BxPA4M4QRFhR0QPozZ2njotsSiBM9vZc+UBeInWSfkyc8Rtmb9DEpLWv7XuU/BPA25kTC6AbBYU/pmg0OiwvHGe5jjQZCMQCBfshHyIwrwMHyYcxjh8EDHCTTNpye4eCcuX7inX0+5Z5xNBHeQ=,iv:d5l8NEBHTHhhEAxiAlDQYjUDgJEKo40s0Uawb+B8LGk=,tag:75kV5Bn95pup145Ru7Ggog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
