apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CF6e+0zKQNLA,iv:CvhI+t7Y/wZyfXr0/SV4yLQ6n9xJdKznbkoHtcpOx9Q=,tag:5maRkNavO7OZ27+uHs5Z1A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VKXvEDIPPqir2i2r/QLg,iv:IJqFm+by+zcuw/k36/wq8cIraVVyih5rdg3NShA1/dg=,tag:wor0Ub1942ClV/iv3yXuWQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4aocNWDygzrSOl12jPDGPvVRlt6+mGqKTlIO7vb8FTBitxgk,iv:a5Jew6mdP7mdUBD9TkCzOL/jDbSrvYtLcZKPsSnDfq8=,tag:zbC0EST1mKP7pvJlfJaBkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNnV4OTVtc1VIcHQyWGJx
            dGxEVkZqNnQyRWpRbWJscG5INUR6ejJTeVFjCk10c1RuZ3I1NTlVWEJNWFFoSExs
            M3ZrcDNwSjJ5LzVRN1FmNWdXYlZnYlkKLS0tIGpqRGFEWU1LVUZQYWdBUUY2NG9E
            cnZoZTlDZkZzVGJUL3BtL0grNWtMYVEK13hB0KfUDICZMgdYnq5/HXoUmIOeXk4P
            fBeqhOiFk6KF66MWHpbTlAWFrRqaFeaeOYzntEa1t2Xg+D4lbk3rSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T21:21:46Z"
    mac: ENC[AES256_GCM,data:aZmC99JM0E/1lSFApqm8Ym2IcUc4V9/ey//gHumzJzc4xtTT2JUugVTMkWEwy1Bqz28AZvjFy1XZui3TOjmXGjotYGRT92cWcdajkGCZMzIsih/QRMn9HxJCLhvWJXe0MY8JCAtTFSIEPoqgKeS8pMrJAJ4miHYAgl0P2nZoE/0=,iv:t2olN7ueMq8joBwjmIyOB3kUm/+48ToCaIGdOBRPRV0=,tag:VYBbEa0VsdCB+X4bBu60hA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
