apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZfCPydaWS5pw,iv:l5f1DumYuFOiCkjn42C3Bpn06ZcwB8RBFz8CMnYq1oI=,tag:kaZ+xbKmCSXabADeneJyKQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:j/ymqdhspKfiqMXWn4hJ,iv:LsenlM/9b0nq3O9E1Y+DEQSc78amrP6bsJUZ42hcUjc=,tag:vDQxj6WvHIDivhX91pSiXA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zFx9rmigqiIUxTEUoQ1nhbtHUf3FMhfDRoJwKyBr5cq1/4El,iv:SZiVIhMqge1I6jXF9yV6kWYUC0FM+LTy4pnGOYWjDyY=,tag:tinhjX7VId3rnFbwRMLDpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aXBzaXBrVzhuWXg3dG4y
            Z2gvZWR5a2RQb1VTUXl0K3ZSb3ZhYVZBOW1zCnN0Y2ExNkdvTGZBcHJ2OFJmcTQz
            aURWNGx3Qy9WZmJSYWZzRWZITE15WXMKLS0tIGF4Q1NMNWJYUjYwdXJENmgrZldT
            Slc3M0YxVXVua1loUHFzYS91bW5wNE0KPloVZYul411Gu5pebKv290CR1JEVQ7Br
            0WnghkGnHosjKLnBAIIb5ZmiOfK7vWwzD21TEyQHHjlX/tM3Mu7TEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T11:05:24Z"
    mac: ENC[AES256_GCM,data:uVE/UUz135OXw+HqGJf3NkorNv5HvUbsgRH+jrxv/iBsgNHo2eWyCR9mhkGiYiOpacL7a83TtMLSFV1ZODClVV/gc2cAIPIdx/zq/BOSeo4n/dS1Z3clB7DuawMZuNiC+B7vYYDsF4/YjrLAZzOz4qOdH8V9fVp9htEfcTGsv88=,iv:+L8nQgS9/3XLxz26mIA1ow8VIYj+FTrVIc0h2t3KS50=,tag:ewst3TcSGANUW9b6TZ6qLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
