apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7hl5kgkzAxr0,iv:8G5IL/DoKwKYGvuInUvj6lcZKS6Jkd9ncc6Q5JT2ctE=,tag:GDh1TJL+4FneePv0SMmDuw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:oO9AcHjivP48UmzbwwGe,iv:TznxsXKfeD2zMZBSAOCnK8n5lVqvLAx+Jy38AsBpGcE=,tag:DaCXJbyJLEXwT2EBuAGGNA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5ndO6WhvPPy1X5ubvHac8XUz6b0z78w4h5MdGvLzZUVWCwAZ,iv:sSS9JzDDSYDGLaqcm5JICYdAy1JbO+iUYCfbA7W5Jjs=,tag:GfYO9zlqA4bID1eCCzoNIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTVNyWTE2emZjMTAvNFNC
            TytvRUxYaEVnRjA1VlgrNzNSeXRzY0VKcjFVCnhFMFBLbGdKcVdXS3MyVHBRdTZu
            dDVJM0NUK2lyZ1FNWlp2MDh6S3BPdzAKLS0tIFNKM2t1cmE4VzVYRE00R0dyT2tH
            SnBaNUZiNTVPSG5KWkhrTzBJMEpmZWsKn8XOXCEsyE6MqGW7JFWdZ1cih9Vm9JOr
            hN7CE6qVWhuaZgM3qB+YGKzIKNAKmTB7mJz6TkqA1uHMVmWTkbjcGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T19:27:05Z"
    mac: ENC[AES256_GCM,data:AUAtv8FN+pLtECG+BPi1jSMH4axBDGDACtuxDIZFVtNo4Sn1h6jN1xGltS4/W2xTstW5azSGVZ1Vh0gILNSDgqdzWOHhDO6ZS53kl8W9ym4UbdmXzTCFpXHuGC5Xdhcn1l31Mu707lOIfxeZoFdRbFO44oh72ZjNr92aiUS7d/s=,iv:3mZCKQqrZ2g0eZVUDmToEcpN5uzpB6IgfANWW/9Oi0c=,tag:wS/ElDE+6z2RVQ+rJSR4gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
