apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZOpFJ8FhGiK4,iv:amN9TyezutuTKXavOnSu1zimv1H/x0p+IM7V75D7ziw=,tag:Nk/1hD850uZHJSehkOS+zQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IxItgXH3CMUBjJ1fQZVG,iv:ss1PvjUEEIAOFsOT0vPqrMyfsqLlpex8+h3hXjcKzvM=,tag:9ERC2ksgwtcSf7mKqp0/IA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gzHwSPX6Ssb9epY09tgeLit4PZUfA/w3QTeQRRidyOSzoded,iv:ThQK1YpCaOKf20OEvyMsUPwLxuPsgsJ9dbAaOC/QKG0=,tag:dzHVknm3thHI+GfH8Ytj6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Ykg3QzRiekZrR2NkdEJr
            QTRuWWpuNVA2MC9BSmd2MHNjZmQwcGp1OW1FCjVORXFxOUU0QW9WczY0dFpYdXFz
            YmVJL003MUVmVVpMdFVkeVBObEx6aWMKLS0tIENvYzVIQ2laSzAzQ2t5ZUpGQkNx
            S2hENDlFV3lwU2c1dWZUNXpSa2tDVW8K74g9w2hA4RcJoysoRhoJWi3m3pUwxqYD
            1m3M5By0FTahmRDH2kwlRLqT65YjYAGohrbI6xCGiGBx1wGanBDOVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T13:12:21Z"
    mac: ENC[AES256_GCM,data:p28sq1EiQJaFk8ftNZMiKy2KGEfiyfqltXABh8UkbsHlUfBtAvs8HR3Q4DgOvjlIB5LGLQm3L6L7h9JPHF+d3I/PpJoKQ7o4nBzjZBpQLXfG8gfuXC5F6Zm81kNS6QsI9jBUhvxVVCa2YZ5bzKeUUiOOt6DlLMpXKYR/T4OOVsA=,iv:ZkCpTVXIqtQZKLp4mmT+5OmQT41d/SC2bE2BSQ8oiFY=,tag:++DtmzbFMRhNwkdWhSFROQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
