apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7yX46jnxT/sa,iv:hGTLBRWrSDEh8MM88XZRr/DnnkqDVPEUSMiURcerkR8=,tag:5KOOpP4xKu9Sk9i7/D7vxw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jhO+oICcV1aoy8ID9SGX,iv:fEc4y3fQzFY7rVURhmWR+mpd3M2j9Ii3jIvR1SVhwKE=,tag:EUo6d9+5rwSiT3r/3CcE/A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:XF1oloPrm/hR/aRzEFe3eWXYT/hPtEu5aV+aZ73tLHqyLfwy,iv:2UURkyVpxoPbsr4nyESdBZFOhRhMu27QfiAz3Bjcax4=,tag:aLt8J4Bbv/dCgWisCd2w+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcUhxUmRYTUE5czlQdnFa
            VTc2VVZFV25UT0V4RUlVdzV6RE85YWFVc1hZCkRYRWpaZ3RUaFd0bi9EaDdOMmhk
            TkViNWhGbXVyT01jUUs2NCtxTXJCY0UKLS0tIFVxOVFMV0o1WXRwa3BSYnNvZ2Fa
            NTdidE5WbVhsSG01L3VpSXRpOUpHTHcKMNSMbi081voMd1vSx+HhMQGVB0EerBiI
            6a0UCGUowwmiN4nwWE1770PnS80zjh9qLFFO1IPVTc5AoxGjLw4BBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T20:52:26Z"
    mac: ENC[AES256_GCM,data:HljFhZFNrwRV+f30Fm76VKIiBdGNoPIH5mwvRVt+JFLDZ2vdN8yhJAFUe3piZeBSltK0CO/3H/Q/zL1GeTVcafGyIuLYsAOUTjwQjWVunewhvj/rGmmURvPC0Dljd9E9IusR0opaUiqKPLStMXQuGIwPHwOYZ8lc+MFpVSPcX7M=,iv:ozd7j3txLDV+FJMuMEDRBVrlhftAY/fcfjDE4y5ZIB4=,tag:84IooeMIAJwoiIFErHdt9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
