---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_ISSUER: letsencrypt-production
  SETTING_EXAMPLE: Global settings for your cluster go in this file, this file is NOT encrypted
