apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:yplhBX1iqkI8jtwrF4wQ7EHU3J8I21jgzHefRCFthrc=,iv:3aUxHF4dMT0vZ5rIK/8wznFcgYlm0cMVbFIk4Mj6unk=,tag:zFyVGVigPt7CjEgiLZVbyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbUFJZWJhb2R4aEtiN1g2
            cEpWdVB3WjROaEpYWHBSc3gwaW1xQTZvaGwwCnNKS3lMZjRWRTlPWVRXMXFMcFRt
            SUlnUzVoOHBXL1ptekJxcndqRjYxTEEKLS0tIFVGQmhRY2xBVm5vcG1Zbkp6aU9Q
            Z0VJUElmczl2UjNQVlczYkpwYW1OY3MKe58oaHHkd/5fJXYD5e1J/1k8G11gktvG
            5zWsomk5d8WUEcj7o5iYpiUMtUQDoi5M+KKUmX2AVCD9oobh+ZiuzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T10:23:06Z"
    mac: ENC[AES256_GCM,data:DhahyE2RmS23OjfuimbymuM5pmX8rEkR+yzkLdd7RCvKF1RL8XrbG3kDk7K5ekLfkKcAQO6T/rhz+bEWrVHWmNPnzGtPR69x5wnrRnSbYcxdgLPx41HfNJdo6/+OxEQZROT5NLMHZlgtZTX8jQemLtfQt45LjN7YgMK7wppWTqo=,iv:DT64xDZoh1SHEA0ug0G6KvjYpkbaNTy5YIwbRNAzI9g=,tag:sfsC1B1JZ3E39k9BgSIXjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
