apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:mEBNN7kyrWZv5m3iDP+jEVtbeM26WT5cgZ95gX3s7pk=,iv:db1vBluLZVNGZNWZHMkXdTc+ug9QA4wtoZsNA3s/jYY=,tag:BLXjNB+jrRkrc7fq8fnMKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UVpQeUZVMmhpZHE4T0Vl
            ZFBjMk5aQ1RZZksyUTU0bXpLUHNVemlLcEVJClY4ODh5MCs5b2JtVnBkL3hzRmEx
            b1ZsMGZmSUVlZHNhK1RSZW9VMFVmakEKLS0tIDNxNFdnNkdEdEt4VUZIRm0ycGFT
            dWZtMjlMdHhZOTRucnNQemxnMU1DQTQKnJal/iC0LhTBws3AZPzS83y61RhN4Tbr
            PSzPhko4t3AVSgJMSbq+R428E+iSUmBzWzMNuLPRVAPqYdE3flMu7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T12:09:06Z"
    mac: ENC[AES256_GCM,data:l6abcC6S5P2scpCBVY9wcr8i41pnhA1fmyzKB9c8EsWaM/BhG2KEZjJmzf4/mrF0Zj0ytNhBct6luCU9rAio3cc1CoDGxVsa0JHocu/nj6Nx6mxC+qC8q7CrPp7kJyV/CPy2pp8G+66pi6fYn+a3PKjSgPjVF3cdfKN+LFpPRYw=,iv:LkIxEiZz9Oudq//z5d305myUf4uoqx2BPkaYiiSQkHY=,tag:dLnQ4xKvGVhgk0VF4SqUEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
