apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:lb7J6YCdKcS/KDAFr6xaeD2zfphtenQYhzDvA43r1nI=,iv:ptWkmu1EI77skKCVJQXcAkbZ3r9y/WKyiff2HYtiPm0=,tag:WlK5R9QlXnKzGFG9Ye4fhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycDlLbC9RZ1RNTVhPN2NC
            TkRybktKN1RrdG10akNOMXBLemM0UUozUlYwCmtLdHBTdUJ5RjhlODhuNkh0NDFk
            U2cyYmFPNDJPdnhEUTcyZURtVVMzYjQKLS0tIDVuNHJVV0ZOUys5MksrTXp6b0gx
            NURuTUxLa2pQRnNHWVZPU25CVVZ0Tm8KevGYgF4RhTTwbh3ya5z9Kxxqs5o8exvN
            CtKbIEM4bYcEIuWJfugcsy0kiW6M322W0psFIpAOdiuTziwmpdKc4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T10:02:58Z"
    mac: ENC[AES256_GCM,data:nfJtf6sC4BaTjWt2nIiwp1kkWk0h07M26MWbfCt4yB8pcZgD6Y5+ysEg605PI+64DkET9gTkYa58864DjLJjtrJV4YWvuvqR5wQid11lPvCB2G+l7mZgBqjDoEMsTLnesLhOC1ZeWgxRXTncMBProFR037hvBFjxbJq1U+1kEeQ=,iv:yMfBxwY2QTRTHlsJOdgoukm+IeDWHtqK+V8d2kpfLQs=,tag:VMluLsGDQo5PHU4TbD2HCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
