apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ieWCT+QtmLtTZcKSOLrF7+mnmt5R07Ml7zYSwWbTkA8=,iv:87xrZ+iBJVyHVALmD62ycbBkKMtuBL1tYoG8/5ZLdVA=,tag:tT/e12l4lWnjQ04fGMgtVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSXVhUEd4ZS9HclRrM2Y2
            WkdaRVlLTEMrQ0hsbm1ubWtqdTV4eG90ZUdjCkZ1UkFCK0lyeXRMN0lFV2FEbVlX
            WU9jY2JTWXpDV2hjV21EV1Z6R1dqd0EKLS0tIFRPY05wdGJJc1ovVHh0ZzQyMjFm
            VGxnSno3UmM3Y0t3N2FNMVM4TUM1R2MKTdaaPKxc9egR3yL+kAVlA0fEuEkjOe2a
            D+i9fIWARx5/EWkg10Mz6+GYUJY1SlF63N/xHX9gRq8LDfw4doEwCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T20:52:26Z"
    mac: ENC[AES256_GCM,data:2nROm41frgiafe7aREvSAJ3uMCP9MzMK4kESKUuqDGinp7eJIsXUAHZhWx5wAZmrkriC6eQ0ly3hFJGu51rA6Si4xuyVQybhIW/N+/bfHg/2nHgLWzBIr+md4HO0Q5EWooiLkBKjGj/luVmC17mbTDBS5yfTTZ5+yAZUcOOzreU=,iv:y80T18a3MloMAYVZJ04MAip+Vag9MtgXNMg18AJfTdY=,tag:DFNkLWdXHWCJVAwCXrLfwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
