apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ANjWBSlHY14Xsi6Er81SjiuEi8zfVfB1Al2BG0tY+2U=,iv:XdxZNfAcZmKGX166zlpHPzRnMoGkfkH8Ztvqpb8DTTI=,tag:PgvBFfSFtmbwppxAQL+R3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY0szcjdxeDg0WlpxZ2NF
            OXhhRjJxRWY4ZVNGOTJMd1R5eEJKVEFiN1M0CjFCNjV1dFFuR2R5cWVyd29zeTR2
            UmZrY3pwOEVaejcrQ3A2d1lvQ2NzTEEKLS0tIFp5OEFWSWIxZHI5M2s0MW12S01Q
            SUhJblVxbzF3dkZZQXpjVmtaejA2c3MKqVejNFIDrFEm5BaX35nEPJpX7/piamvj
            g7aizhrRjEARcZElOLyTOZwigCRhhSUN6prUfY+7DzaD1gMh9//qdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T16:14:42Z"
    mac: ENC[AES256_GCM,data:doN1iSiiD24Ho+mCX5XE32qRlXdNsWXx7So8hOdBXvFUprpU7aT8I3DpQRGQiQoCEogSw0TVKUys0NbOnvgp1TsRhj1yvu6M0cX+yUk8pZtBvlK7zp3YbcElf8WMvN9s9zh2puA8HGd9LjivcZcxyPRWUbDcZR9shub59PexfTo=,iv:grRro/d4OCXxndNFMo+rGTiYaOYwsejypnQlaQULwr8=,tag:T2P3c//euknl9f0PqjJT6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
