apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:daPpvFKdd069OBhojo8fCa3rYPkJH4vRzp6K9rNHBdY=,iv:Xg4U3G7ghtq4oXoz+9FqnxUfJ1hlPKbZ0LPlWefLGrc=,tag:vWyIwHkq86KrMI+KnZtFjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLa1QzakNleURldjlxVS9z
            Ri9KdHhncWlEbitHTGhUbFFVS2MrNVdWeUgwCk9yM2ZFaVVlSXhCS1U1MEZiVFBL
            elgxSlBSMjFZdUM3QlhQU0YxbC92aXMKLS0tIEpOeml6WnV4NXMrY21xUUVWSjZl
            aGdhRUIxUExMQXNiazNWZXFzTElRNGcKAinW8TJk5+/6GaHGzFSM+n79FvpT5SjS
            /kgMVBwEG6rG+lKZjSl61gOQPqnNVXASzSQUQg8qhnMsY9Nc+WG2aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T12:21:35Z"
    mac: ENC[AES256_GCM,data:58hqYS9ZSxF+2y43k8vn/BEJGS17WszR+norz82csLkDqA6yzOEXg7YAIyNavwO62y1BH13ZVtwiPqVt+oI2aI5dYObwrjgHHBSqkFHK/MWCVkBAQhRIhWHyUYKTWl1os9EXhPCzFvSQiqdtDIU669xzwxqZ6vhB2NM8YpwGLuU=,iv:1pkhLGVBPLCW6yvAmTyYYpgDyRnwTli2z68W8XAZ1cM=,tag:p5iaQ7Wd5ZpJaDBs2VFUhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
