apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:OUy88ZiYhdl3AUwSYU3psOpSjYn7bIK3HuDNWpflKd0=,iv:eNkGHwuxjeoiZRDIZ/XgmWhEoprU2Vu7Ldthgtww/TQ=,tag:kg7Q1A8epwsmMlnYMvDZbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYWJoUy8yTStKRTdIVUNK
            MlJMTkZWci9PSDJDWXFMSS8ra3NnaFlXd1RZCnVmaDZSVS94cUVrcXF1TXl3enQw
            OVZmc29XemM5cXNrcFhpL1YrdFlzdkUKLS0tIEozUnV1RmdZRER2WjJGVWtTQUVr
            Q0JoVDZoRXRrNzRoRDdJVmZWOEd2R2MKODM4anX4KdSIxikBBk9Al9Mb18fDJWVz
            wHncAaBl53YoYBoDN+6rr2fqdXscr8nW3KHK9cR0w3u2xIQ9iu45Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T20:22:54Z"
    mac: ENC[AES256_GCM,data:3/rY06FyRmrx39wYmOpbiKxTcmmmImOq6MFnw3MlVr+wakoRv8WOt+d808xlUTTJm19N7/RjRShCsnYeSYPF3dmQdqZ6MR2j8MW3yYCgxQbl+iJn7sKtsKhYL+cSf5w9ZrIELgZ068owvbZNA0CSxUrAOkOEwdKbIJDKkBoKMDE=,iv:cB6NOr+K4Ay0aV2Bwe3x7yggeEHR5qSNdmJSlwBr/9k=,tag:07DDhyy0GJLeTHVfGwE2iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
