apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UaoqK9rZ8Lv29g5usg+EjNkNiKAhXI/3s89rJHIgMN/hoS6gmhF9+g==,iv:yGnwTwoMJRfVTEIR4SY6zKlblbk9dRPSxT+ZdMc/epc=,tag:WCDXmetPC6PTva9mNPceUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQUdybmgyQW40VUliVWlV
            cmlUUlB5cFVTejRjdkpvY3BwdCsrNFhydUhBCndlcWdMOHo1OUtJbE9NYm5pQkFI
            ZDIrdEJqc0RZOXRHV3d6UStsbHpwNk0KLS0tIEJ5S0IxTjJYNFR5ZFhHZmV5Mzc2
            eWxGbDBGVEFybmQwV2dqMmpTaDZxZlkKOmr/3ENnYo1Vn6DsAdC0g+1kvm5P2BcV
            zfxVVJgYgKfTgHs+TZ07nyvVUwJoWLI6jm1QW6gea7GINUYiSp7Z1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T21:21:46Z"
    mac: ENC[AES256_GCM,data:kWUgIA5pZLLvCUeKV6ZetW6e73BtoMo960JTp/qZxBBosSDP6BSIFZB3lp+0jQb9xd8/eteSI+ewGwanEcn3W007Zds5k7sOW1NL+rHgREaY1aNjqECFSDQA80d5WT06jZvH7GDWQ4PiFEZsaf5D93o6nMtf84jO/Z6vOBAvw5o=,iv:QhmZNbrNg+LPt3IePoql7rUrSkHhy3if8U9K78Dbv5w=,tag:iKp2QV/OstWDE68at2k/NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
