apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:FuDiN+r/Cm8qFGR8fGnC94B8DutvgMzbCfBh65ifpCbvbLgkq16Xyg==,iv:RBRVObHFReljZsqRvaPyy/gQwgN4E8ebammLJcfbLsk=,tag:wOkFTX1QUhGwQV6xJpbozg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQVRwTVZ0WHBPZ2dlSVFk
            NExqTEdMblZpVmt4bUd2Qnp6MGhsU1ZOM3hVCm90MGx1ODZ2cDJTN1JnclBBcytV
            S1hEWWR6QlY0RXNlc1RWZ0ozL1o5SzQKLS0tIFZ6bkNsNlR4QmtYMHdrb2IxTGRT
            RVNOV2hvL3Q0aDVFVVBURTlCNGN4RkkK5+yjsOAbdM4SIN93pnEC4nVE6dXh91av
            G7aXw/3U5bAYrgmnh1qu0Dk86xU/HegKami3rD9qggXyYgZH7ujv8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T22:02:40Z"
    mac: ENC[AES256_GCM,data:TbchREa7IgmpBWyCEMVln3wDdddtDXUpr8VGZEFV51XNx/htfSOEcLaX0W+qU9+AbKWH+/rQ3YDiQ0CRhEPL5sciP8FHOGjWl2sXTsYHbMs+Gqd5x2IW2PwqSQn+/NYNFYPr/MeziPLv6xW/VsVe/rUkpb4dW9wyxVQi0P1Qqz8=,iv:ugArqTi9McBZa11B1zBiWS0KPaHZ5JYN8aO0kRQYrcQ=,tag:ptqqOU31o5uJw9hkGdXvqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
