apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:zhe3y1cujpuetdLcKA4SAv4uyjqfPlwSMcMxAIIkYQDB+mEGhLssug==,iv:ULw6zH+xyRiNXZBnfoGY9NqV6UgNXfr5HaUry8ruYDs=,tag:ykWWFwc7LYVZOqip1ycEuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sp9tzc7nxhnygapyn00e7sp677gdsdsf9vz4w78q5kfkd8er39lqe2mph4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcEI4WklBQlRxR1Z3VC9j
            QmZyUHNDT2Mzd0hRK3A2YWlEYm9ML2tzRG1ZClRQbnQyU1UzWWJ2ZXBiTUFoZ0lG
            d1VTZCtSbTh4dit5U3VIVXozNys0eTAKLS0tIHFtU0RDM2lFNjB0dXI2L1c0Vkxj
            YVhFME5paUtGVkFRdHNJU3dnajh0aGMKgXw4kjKUs3L6F0tIOl+mttADlSCGyabE
            yeapWehgfjzBhxpl3D4Zugb+4TJXo2E0Ks+cPblub4yNzy9soOoQlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T21:26:32Z"
    mac: ENC[AES256_GCM,data:rpI+Nn4Hevd0DrDPTz2fxR9dvPCPYJ+Mzx91AM6/zY0+gRxc2EBg5KMNUlGVEXo0boUPS71FSMxWhabU8p306cslMtZxnUft7gMRlgOwdp9Ew2ypZf4K++yEOeDwjRuiSuAO0o9iwNLm+2M4jbktXVc70qYax+2nvd/lQ3MOGu8=,iv:Lhv/qJPRraJrvd8qLEMcFhoG3E0I30h0gBRPqfw0QuY=,tag:4PC4pAm87llxX8c0nkXvOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
